config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'reports#index'
  resources :users, only: :show
  resources :reports do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '日次' },
    { id: 3, name: '週次' },
    { id: 4, name: '月次' },
    { id: 5, name: '至急' },
    { id: 6, name: '重要' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :reports
end

app/models/format.rb
class Format < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '日報' },
    { id: 3, name: '成果管理表' },
    { id: 4, name: 'ビジネス文書' }
  ]

  include ActiveHash::Associations
  has_many :reports
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :format
  belongs_to :category

  validates :format_id, :category_id, :title, :headline, :text, :date, presence: true
  validates :title, length: { maximum: 15 }
  validates :headline, length: { maximum: 140 }
  validates :text, length: { maximum: 1000 }
  validates :format_id, :category_id, numericality: { other_than: 1 }

  def self.search(search)
    if search != ''
      Report.where('text LIKE(?)', "%#{search}%")
    else
      Report.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reports

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :encrypted_password, :password, :password_confirmation,
            format: { with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]{6,}/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :position])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_report, only: [:show, :edit, :update, :destroy, :access_limit]
  before_action :access_limit, only: [:edit, :destroy]

  def index
    @reports = Report.order('created_at DESC').all.page(params[:page]).per(10)
    if user_signed_in?
      @reports = Report.order('created_at DESC').all.page(params[:page]).per(10)
      @to_reports = Report.where(receiver: current_user.name).order('created_at DESC').all.page(params[:page]).per(5)
    end
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    if @report.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @report.update(report_params)
      redirect_to report_path(@report.id)
    else
      render :edit
    end
  end

  def destroy
    if @report.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @keyword = params[:keyword]
    @reports = Report.search(@keyword).order('created_at DESC').all.page(params[:page]).per(10)
    @to_reports = Report.search(@keyword).where(receiver: current_user.name).order('created_at DESC').all.page(params[:page]).per(5)
  end

  private

  def report_params
    params.require(:report).permit(:title, :headline, :text, :format_id, :category_id, :date,
                                   :receiver).merge(user_id: current_user.id)
  end

  def set_report
    @report = Report.find(params[:id])
  end

  def access_limit
    redirect_to root_path if current_user.id != @report.user_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name
    @reports = current_user.reports
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReportApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/_report.html.erb
<li class="report">
        <div class="report-title">
          <%= link_to report.title, report_path(report.id) %>
        <%= link_to report_path(report.id) do %>
        </div>
          <% if report.category_id == 2 %>
          <%= image_tag("text1_mainichi.png",class:"report-image") %>
          <% elsif report.category_id == 3 %>
          <%= image_tag("text2_maisyu.png",class:"report-image") %>
          <% elsif report.category_id == 4 %>
          <%= image_tag("text3_maitsuki.png",class:"report-image") %>
          <% elsif report.category_id == 5 %>
          <%= image_tag("text_shikyuu.png",class:"report-image") %>
          <% elsif report.category_id == 6 %>
          <%= image_tag("text_juuyou.png",class:"report-image") %>
          <% elsif report.category_id == 7 %>
          <%= image_tag("text_syorui.png",class:"report-image") %>
          <% end %>
        <% end %>
        
        <div class="report-users">
              <div class="report-user">
                  from <%= report.user.name %>
              </div>
              <div class="report-receiver">
                  to <%= report.receiver %>
              </div>
        </div>
      </li>

app/views/reports/edit.html.erb
<div class="new-report">
  <header><%= render "shared/sub-header" %></header>

  <div class="new-main">
    <%= form_with model: @report, local: true do |f| %>
      <div class="report-box">
        <h1 class="new-top-title">Edit Report</h1>
        <%= render 'shared/error_messages', model: f.object, resource: @report %>
        <div class="new-nav">日付</div>
        <%= f.date_field :date, class:"new-date", placeholder:"年/月/日"%>
        <div class="new-nav">書式</div>
        <%= f.collection_select(:format_id, Format.all, :id, :name, {}, {class:"select-box"}) %>
        <div class="new-nav">カテゴリー</div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
        <div class="new-nav">タイトル</div>
        <%= f.text_field :title, class:"new-title", placeholder:"15文字以内", maxlength:"15" %>
        <div class="new-nav">件名</div>
        <%= f.text_area :headline, class:"new-headline", placeholder:"140文字以内", maxlength:"140" %>
        <div class="new-nav">本文</div>
        <%= f.text_area :text, class:"new-text", placeholder:"1000文字以内", maxlength:"1000", row:"7" %>
        <div class="new-nav">提出先</div>
        <select name="report[receiver]", class="new-receiver">
          <option value="">提出先を選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%=user.name %>><%= user.name %></option>
          <% end %>
        </select>
        <%= f.submit "保存" ,class:"btn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/reports/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <% if user_signed_in? %>
    <div class="sub-title">Report to You</div>
    <ul class="report-lists">
      <% @to_reports.each do |report| %>
          <%= render partial: "report", locals: { report: report }%>
      <% end %>
    </ul>

    <%= link_to(new_report_path, class: "post-btn") do %>
    <span class="btn-text">New Report</span>
    <% end %>
  <% end %>

  <div class="main-bar">
    <div class="main-title">Report List</div>
    <div class="page-btn"><%= paginate @reports %></div>
  </div>
  <ul class="report-lists">
    <%= render partial: "report", collection: @reports %>
  </ul>
  
</div>

<%= render "shared/footer" %>

app/views/reports/new.html.erb
<div class="new-report">
  <%= render "shared/sub-header" %>

  <div class="new-main">
    <%= form_with model: @report, local: true do |f| %>
      <div class="report-box">
        <h1 class="new-top-title">New Report</h1>
        <%= render 'shared/error_messages', model: f.object, resource: @report %>
        <div class="new-nav">日付</div>
        <%= f.date_field :date, class:"new-date", placeholder:"年/月/日"%>
        <div class="new-nav">書式</div>
        <%= f.collection_select(:format_id, Format.all, :id, :name, {}, {class:"select-box"}) %>
        <div class="new-nav">カテゴリー</div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
        <div class="new-nav">タイトル</div>
        <%= f.text_field :title, class:"new-title", placeholder:"15文字以内", maxlength:"15" %>
        <div class="new-nav">件名</div>
        <%= f.text_area :headline, class:"new-headline", placeholder:"140文字以内", maxlength:"140" %>
        <div class="new-nav">本文</div>
        <%= f.text_area :text, class:"new-text", placeholder:"1000文字以内", maxlength:"1000", row:"7" %>
        <div class="new-nav">提出先</div>
        <select name="report[receiver]", class="new-receiver">
          <option value="">提出先を選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%=user.name %>><%= user.name %></option>
          <% end %>
        </select>
        <%= f.submit "作成する" ,class:"btn" %>
        </div>
      </div>
    <% end %>
  </div>
  
  <%= render "shared/footer" %>
</div>

app/views/reports/search.html.erb
<%= render "shared/header" %>

<div class="main">
  <% if user_signed_in? %>
    <div class="sub-title">
      Report to You <span class="search-word">--- 検索ワード：<%= @keyword %></span>
    </div>
    <ul class="report-lists">
      <% @to_reports.each do |report| %>
          <%= render partial: "report", locals: { report: report }%>
      <% end %>
    </ul>

    <%= link_to(new_report_path, class: "post-btn") do %>
    <span class="btn-text">New Report</span>
    <% end %>
  <% end %>

  <div class="main-bar">
    <div class="main-title">Report List</div>
    <div class="page-btn"><%= paginate @reports %></div>
  </div>
  <ul class="report-lists">
    <%= render partial: "report", collection: @reports %>
  </ul>
  
</div>

<%= render "shared/footer" %>

app/views/reports/show.html.erb
<%= render "shared/header" %>
<main class="show-report-main">
  <div class="show-report-content">
    <div class="report-top">
      <div class="show-report-title"><%= @report.title%></div>
      <div class="show-report-date"><%= @report.date.strftime("%Y年 %m月 %d日") %></div>
    </div>

    <div class="user-profile">
      <div class="user-position-box">
        <div class="show-user-string">所属</div>
        <div class="user-position"><%= @report.user.position %></div>
      </div>
      <div class="user-name-box">
        <div class="show-user-string">氏名</div>
        <div class="user-name"><%= @report.user.name %></div>
      </div>
    </div>
 
    <div class="report-content">
      <div class="show-report-string">件名</div>
      <div class="report-headline" ><%= @report.headline %></div>
      <div class="show-report-string">内容</div>
      <div class="report-text"><%= @report.text%></div>
    </div>

  </div>
  <div class="show-btn">
    <%= link_to "戻る", root_path, class:"return-btn" %>
    <% if user_signed_in? %>
      <% if @report.user_id == current_user.id %>
        <%= link_to "編集", edit_report_path(@report.id), class:"edit-btn" %>
        <%= link_to "削除", report_path(@report.id), method: :delete, class:"delete-btn" %>
      <% end %>
    <% end %>
  </div>
</main>
<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <h1 class="footer-text"><%= link_to "Report App", root_path, class: "footer-name" %></h1>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class='top-page-header'>
    <h1><%= link_to 'ReportApp', root_path, class:'app-name' %></h1>
    <%= image_tag("header.jpg",class:"header-image") %>
  </div>  
  
  <div class="second-bar">
    <%= form_with(url: search_reports_path, local: true, method: :get, class: "search-form") do |f| %>
        <%= f.text_field :keyword, placeholder:'キーワードから探す', class:"input-box" %>
        <div class="search-btn">
          <%= image_submit_tag("search.png", class:"search-icon", alt:"search") %>
        </div>
    <% end %>
  

    <ul class='lists-right'>  
      <% if user_signed_in? %>
        <li><%= link_to current_user.name, "/users/#{current_user.id}", class: "user-nickname" %></li>
        <li><button><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></button></li>
      <% else %>
        <li><button><%= link_to 'ログイン', new_user_session_path, class: "login" %></button></li>
        <li><button><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></button></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_sub-header.html.erb
<header class="sub-header">
  <h1><%= link_to 'ReportApp', root_path, class:'sub-app-name' %></h1>
  <%= image_tag("header.jpg",class:"sub-header-image") %>
</header>

app/views/users/_report.html.erb
<li class="report">
        <div class="report-title">
          <%= link_to report.title, report_path(report.id) %>
        <%= link_to report_path(report.id) do %>
        </div>
          <% if report.category_id == 2 %>
          <%= image_tag("text1_mainichi.png",class:"report-image") %>
          <% elsif report.category_id == 3 %>
          <%= image_tag("text2_maisyu.png",class:"report-image") %>
          <% elsif report.category_id == 4 %>
          <%= image_tag("text3_maitsuki.png",class:"report-image") %>
          <% elsif report.category_id == 5 %>
          <%= image_tag("text_shikyuu.png",class:"report-image") %>
          <% elsif report.category_id == 6 %>
          <%= image_tag("text_juuyou.png",class:"report-image") %>
          <% elsif report.category_id == 7 %>
          <%= image_tag("text_syorui.png",class:"report-image") %>
          <% end %>
        <% end %>
        
        <div class="report-users">
              <div class="report-user">
                  from <%= report.user.name %>
              </div>
              <div class="report-receiver">
                  to <%= report.receiver %>
              </div>
        </div>
</li>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="main">
 <div class="sub-title"><%= @name %>'s Report</div>
  <ul class="report-lists">
    <%= render partial: "report", collection: @reports %>
  </ul>
</div>
<%= render "shared/footer" %>